### ISSUE TITLE
When will this be available to buy from you?

### ISSUE THREAD

**Issue by crabdancing** [simplefoc/SimpleFOC-DriveShield#2]
I'd love to play around with one of these! :3

**Comment by askuric** [comment]
Hey @crabdancing,

I'm hoping to have them in the shop within next 3-6 weeks. 
I've still got a few of the testing boards so if you'd wanna have a test version, send me a PM. :D

**Comment by crabdancing** [comment]
Oh, awesome -- I'd love that! I found you on Discord, so I sent a message there. ^w^
